<?php

namespace App\Services\Users;

use DB;
use App\Services\Service;
use App\Models\User;
use App\Models\Category;
use App\Models\UserLimits;
use App\Helpers\RoleHelper;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;

class UserCreationService extends Service
{
    use UserService;

    public const RESULT_INVALID_LIMIT = 0;
    public const RESULT_SUCCESS = 1;

    public function __construct(
        private Request $_request
    ) {

        $user = new User();
        $user->full_name = $this->_request->full_name;
        $user->username = $this->_request->username ?: strtolower(str_replace(' ', '', $this->_request->full_name));

        // TODO: Edge case: Their full name was unique, they did not enter a custom username, but the autogenerated username above is not unique
        // Possible Cause: "Tad hgBoyle" as full name instead of "Tadhg Boyle" -> would make "tadhgboyle" as username, which might already exist
        // Three options:
        // 1. Leave as is. Slightly slower as we need another query, but it works
        // 2. Instead of replacing whitespace with "" when making the username, replace it with "_"
        // 3. Always add a random number to the end of all autogenerated usernames

        // Using User::where(...)->count() does not work while testing for some reason
        if (DB::table('users')->where('username', $user->username)->count() > 0) {
            $user->username = $user->username . mt_rand(0, 100);
        }

        $user->balance = $this->_request->balance ?: 0;
        $user->role_id = $this->_request->role_id;

        // TODO: This returns true if there is only 1 role which is a non-staff role... 
        if (RoleHelper::getInstance()->isStaffRole($this->_request->role_id)) {
            $user->password = bcrypt($this->_request->password);
        }

        $user->save();

        // Update their category limits
        foreach ($this->_request->limit as $category_id => $limit) {

            // Default to limit per day rather than week if not specified
            $duration = $this->_request->duration[$category_id] ?? UserLimits::LIMIT_DAILY;

            // Default to -1 if limit not typed in
            if ($limit == null || !isset($limit) || empty($limit)) {
                $limit = -1;
            }

            if ($limit < -1) {
                $this->_message = 'Limit must be -1 or above for ' . Category::find($category_id)->name . '. (-1 means no limit)';
                $this->_result = self::RESULT_INVALID_LIMIT;
                return;
            }

            UserLimits::create([
                'user_id' => $user->id, 
                'category_id' => $category_id,
                'limit_per' => $limit, 
                'duration' => $duration, 
                'editor_id' => auth()->id()
            ]);
        }

        $this->_result = self::RESULT_SUCCESS;
        $this->_message = 'Created user ' . $user->full_name . '.';
        $this->_user = $user;
    }

    public function redirect(): RedirectResponse
    {
        switch ($this->getResult()) {
            case self::RESULT_SUCCESS:
                return redirect()->route('users_list')->with('success', $this->getMessage());
            default:
                return redirect()->back()->withInput()->with('error', $this->getMessage());
        }
    }
}
