<?php

namespace App\Http\Controllers;

use Validator;
use App\User;
use App\UserLimits;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UsersController extends Controller
{

    public function new(Request $request)
    {
        // TODO: If the selected role is camper, but they accidentally typed something into "password" field, it sends an error to confirm, 
        // even though it is "required_unless"... Laravel issue?
        $validator = Validator::make($request->all(), [
            'full_name' => 'required|min:4|unique:users,full_name',
            'username' => 'nullable|min:3|unique:users,username',
            'balance' => 'nullable|nullable',
            'role' => 'required|in:camper,cashier,administrator',
            'password' => 'required_unless:role,==,camper|nullable|required_with:password_confirmation|same:password_confirmation|min:6',
        ]);
        if ($validator->fails()) {
            return redirect('/users/new')
                ->withInput($request->all())
                ->withErrors($validator);
        }

        // Create a new User object and hash it's password if required by their role
        $user = new User();
        $user->full_name = $request->full_name;
        if (empty($request->username)) $user->username = strtolower(str_replace(" ", "", $request->full_name));
        else $user->username = $request->username;

        // TODO: Edge case: Their full name was unique, they did not enter a custom username, but the autogenerated username above is not unique
        // Possible Cause: "Tad hgBoyle" as full name instead of "Tadhg Boyle" -> would make "tadhgboyle" as username, which might already exist
        // Three options:
        // 1. Leave as is. Slightly slower as we need another query, but it works
        // 2. Instead of replacing whitespace with "" when making the username, replace it with "_"
        // 3. Always add a random number to the end of all autogenerated usernames
        if (User::where('username', $user->username)->first() != null) $user->username = $user->username . mt_rand(0, 100);

        $balance = 0;
        if ($request->balance != null || $request->balance != "") $balance = $request->balance;

        $user->balance = $balance;
        $user->role = $request->role;

        if ($request->role != "camper") {
            $user->password = bcrypt($request->password);
        }
        $user->save();

        // Update their category limits
        foreach ($request->limit as $category => $limit) {
            $duration = 0;
            // Default to limit per day rather than week if not specified
            // TODO: Fix "Undefined index ['category']" when only setting limits for somethings...
            if (($request->duration[$category] == NULL || $request->duration[$category] == "") ? $duration = 0 : $duration = $request->duration[$category]);
            // Default to unlimited limit if not specified
            if ($limit == NULL || $limit == "") $limit = "-1";
            if ($limit < -1) {
                return redirect()
                    ->back()
                    ->with('error', 'Limit must be -1 or above for ' . ucfirst($category) . '. (-1 means no limit, 0 means not allowed.)')
                    ->withInput($request->all());
            }
            UserLimits::updateOrCreate(
                ['user_id' => $user->id, 'category' => $category],
                ['limit_per' => $limit, 'duration' => $duration, 'editor_id' => $request->editor_id]
            );
        }
        return redirect('/users')->with('success', 'Created user with name ' . $request->full_name . '.');
    }

    public function edit(Request $request)
    {
        // TODO: Apply new validation logic from above
        $validator = Validator::make($request->all(), [
            'full_name' => 'required|min:4',
            'username' => 'required',
            'balance' => 'required|numeric',
            'role' => 'required',
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withInput($request->all())
                ->withErrors($validator);
        }

        $password = NULL;
        $old_role = strtolower(DB::table('users')->where('id', $request->id)->pluck('role')->first());
        $new_role = strtolower($request->role);
        $staff_roles = array(
            'cashier',
            'administrator'
        );
        // Update their category limits
        foreach ($request->limit as $category => $limit) {
            $duration = 0;
            if ($request->duration[$category] == "" ? $duration = 0 : $duration = $request->duration[$category]);
            if ($limit == "") $limit = "-1";
            if ($limit < -1) {
                return redirect()->back()->with('error', 'Limit must be above -1 for ' . ucfirst($category) . '. (-1 means no limit, 0 means not allowed.)')->withInput($request->all());
            }
            UserLimits::updateOrCreate(
                ['user_id' => $request->id, 'category' => $category],
                ['limit_per' => $limit, 'duration' => $duration, 'editor_id' => $request->editor_id]
            );
        }

        // TODO: This next part is fucking terrifying. Probably can find a better solution.
        // If same role or changing from one staff role to another
        if (($old_role == $new_role) || (in_array($old_role, $staff_roles) && in_array($new_role, $staff_roles))) {
            DB::table('users')
                ->where('id', $request->id)
                ->update(['full_name' => $request->full_name, 'username' => $request->username, 'balance' => $request->balance, 'role' => $request->role]);
            return redirect('/users')->with('success', 'Updated ' . $request->full_name . '\'s profile.');
        }
        // If old role is camper and new role is staff
        else if (!in_array($old_role, $staff_roles) && in_array($new_role, $staff_roles)) {
            if (isset($request->password)) {
                if ($request->password == $request->password_confirmation) {
                    $password = bcrypt($request->password);
                } else {
                    return redirect()->back()->with('error', 'Please confirm the password.')->withInput($request->all());
                }
            } else {
                return redirect()->back()->with('error', 'Please enter a password.')->withInput($request->all());
            }
        }
        // If new role is camper
        else $password = NULL;

        DB::table('users')
            ->where('id', $request->id)
            ->update(['full_name' => $request->full_name, 'username' => $request->username, 'balance' => $request->balance, 'role' => $request->role, 'password' => $password]);
        return redirect('/users')->with('success', 'Updated ' . $request->full_name . '\'s profile.');
    }

    public function delete($id)
    {
        $name = User::where('id', $id)->first()->full_name;
        User::where('id', $id)->delete();
        return redirect('/users')->with('success', 'Deleted user ' . $name);
    }
}
